services:
  vkusvill-bot:
    build: .
    container_name: vkusvill-bot
    restart: unless-stopped
    environment:
      - GIT_COMMIT_HASH=${GIT_COMMIT_HASH:-unknown}
      - GIT_COMMIT_DATE=${GIT_COMMIT_DATE:-unknown}
      - GIT_BRANCH=${GIT_BRANCH:-unknown}
    volumes:
      - ./app.py:/app/app.py
      - ./bot:/app/bot
      - ./config.yaml:/app/config.yaml
      - ./prompts:/app/prompts
      - ./logs:/app/logs
      - ./db:/app/db
      - ./assets:/app/assets
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

